services:
  postgres:
    image: postgres:15
    container_name: grocery-store-db
    environment:
      POSTGRES_DB: grocery_store_db
    env_file:
      - src/main/resources/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata-grocery-store:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata-grocery-store:
